modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="betterbiomesrewrite"
version="0.2"
displayName="BetterBiomesRewrite"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Xenox"
description='''
Overhauls the Biomes of Minecraft.
'''

[[dependencies.betterbiomesrewrite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




